// flow-typed signature: b8b4d142d6adcfba57dc16fe0c53decc
// flow-typed version: <<STUB>>/babel-preset-stage-2_v^6.5.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-stage-2/index' {
  declare module.exports: $Exports<'babel-preset-stage-2'>;
}
declare module 'babel-preset-stage-2/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-2'>;
}
