// flow-typed signature: 31ef31a28d7f0ed6b69c63744e2dc8b4
// flow-typed version: <<STUB>>/liner_v^0.3.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'liner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'liner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'liner/example' {
  declare module.exports: any;
}

declare module 'liner/fileread' {
  declare module.exports: any;
}

declare module 'liner/test/liner.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'liner/example.js' {
  declare module.exports: $Exports<'liner/example'>;
}
declare module 'liner/fileread.js' {
  declare module.exports: $Exports<'liner/fileread'>;
}
declare module 'liner/index' {
  declare module.exports: $Exports<'liner'>;
}
declare module 'liner/index.js' {
  declare module.exports: $Exports<'liner'>;
}
declare module 'liner/test/liner.test.js' {
  declare module.exports: $Exports<'liner/test/liner.test'>;
}
